[WebDAV]
# 监听地址 0.0.0.0 表示局域网所有设备可访问
host = 0.0.0.0
# 服务端口（可自定义）
port = 8000
# 本地共享目录（绝对路径/相对路径都支持）
root_path = ./webdav_share
# Windows 示例：
# root_path = D:\办公区文件

[Auth]
# 是否开启账号密码认证 True/False
enable_auth = True
username = admin
password = 123456

[Log]
debug = False